config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :old_expenses
  resources :expenses
  resources :incomes
  resources :mobile

  resources :dashboard

  resources :work_expenses_in
  resources :work_expenses_out
  resources :old_incomes

end

app/models/income.rb
# == Schema Information
#
# Table name: incomes
#
#  id               :integer          not null, primary key
#  income_source_id :integer
#  amount           :decimal(, )      not null
#  comments         :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  year             :integer          not null
#  month            :integer          not null
#  currency_id      :integer          not null
#

class Income < ActiveRecord::Base

  belongs_to :income_source
  belongs_to :currency
  acts_as_taggable # Alias for acts_as_taggable_on :tags

  scope :between_dates, -> (start_year, start_month, end_year, end_month) {
    where(year: start_year..end_year).where(month: start_month..end_month)
  }

  scope :income_groups, -> {
    Income.joins(:currency)
    .group('currencies.name')
    .joins(:income_source)
    .group('income_sources.name')
    .sum(:amount)
  }

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  before_filter :sanitize_income_params
  before_action :set_incomes, on: :index

  def show
    @income = Income.find(params[:id])
  end

  def create
    @income = Income.new(income_params)
    if @income.save!
      redirect_to action: "new"
    end
  end

  def index
    @incomes.order(:created_at) if @incomes.present?
    @summary ||= @incomes.joins(:currency).group('currencies.name').sum(:amount) if @incomes.present?
  end

  def new
    @income = Income.new
  end

  def edit
    @income = Income.find(params[:id])
  end

  def update
    @income = Income.find(params[:id])

    if @income.update(income_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @income = Income.find(params[:id])

    @income.destroy!
    redirect_to action: "index"
  end

  def income_params
    params.require(:income).permit(:income_source_id, 
                                    :amount, :comments, :year, 
                                    :month, :currency_id)
  end

  def sanitize_income_params
    params[:income_source_id] = params[:income_source_id].to_i
    params[:amount] = params[:amount].to_i
    params[:year] = params[:year].to_i
    params[:month] = params[:month].to_i
    params[:currency_id] = params[:currency_id].to_i
  end

  def set_incomes
    if params[:filter].present?
      @incomes = Income.all
      @incomes = Income.where(year: params[:filter][:year]) if params[:filter][:year].present?
      @incomes = @incomes.where(month: params[:filter][:month]) if params[:filter][:month].present?      
      @incomes = @incomes.joins(:income_source).where(income_sources: { name: params[:filter][:income_source] }) if params[:filter][:income_source].present?
    end
  end

  def set_income
    @income = Income.find(params[:id])
  end

end

app/helpers/income_helper.rb
module IncomeHelper
end

app/views/incomes/create.html.erb
<h1>Income#create</h1>
<p>Find me in app/views/income/create.html.erb</p>

app/views/incomes/edit.html.erb
<h1>Expenses#update</h1>
<p>Find me in app/views/incomes/update.html.erb</p>

<h1>Edit income</h1>

<%= form_for(@income) do |f| %>

  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@income.errors.count, "error") %> prohibited
        this income from being saved:
      </h2>
      <ul>
        <% @income.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :year %>
  <%= f.text_field :year, value: DateTime.now.year %>
  <br>
  <%= f.label :month %>
  <%= f.text_field :month, value: DateTime.now.month %>
  <br>
  <%= f.label :income_source_id %>
  <%  income_array = IncomeSource.active.map { |src| [src.name, src.id] } %>
  <%= f.select :income_source_id, income_array %>
  <br>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <br>
  <%= f.label :currency_id %>
  <%  curr_array = Currency.all.map { |cur| [cur.name, cur.id] } %>
  <%= f.select :currency_id, curr_array.sort %>
  <br>
  <%= f.label :comments %>
  <%= f.text_field :comments %>
  <br>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<div class="filter_options_container">
  <form class="filter_form">
    <%= select("filter", "year", ['',2013, 2014, 2015, 2016, 2017], selected: params[:filter].present? ? params[:filter][:year] : DateTime.now.year) %>
    <%= select("filter", "month", ['',1,2,3,4,5,6,7,8,9,10,11,12], selected: params[:filter].present? ? params[:filter][:month] : DateTime.now.month) %>
    <%= select("filter", "income_source", IncomeSource.pluck(:name).push(''), selected: params[:filter].present? ?params[:filter][:income_source] : '') %>
    <input type="submit" value="Filter" />
  </form>
</div>

<% if @summary.present? && @incomes.present? %>
  <% @summary.each do |k,v| %>
    <h3><%= k  %>: <%= number_to_currency(v, precision: 0)  %></h3>
  <% end %>

  <h1>Income</h1>
  <table class="table table-hover">
    <tr>
      <th>year</th>
      <th>month</th>
      <th>category</th>
      <th>amount</th>
      <th>currency</th>
      <th>comments</th>
    </tr>

    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.year %></td>
        <td><%= income.month %></td>
        <td><%= income.income_source.name %></td>
        <td><%= income.amount %></td>
        <td><%= income.currency.name %></td>
        <td><%= income.comments %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Delete', income_path(income),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/incomes/new.html.erb
<h1>New Income</h1>
<%= bootstrap_form_for @income, url: {action: "create"} do |f| %>
  <%= f.text_field :year, value: DateTime.now.year %>
  <%= f.text_field :month, value: DateTime.now.month %>
  <%  income_array = IncomeSource.active.map { |src| [src.name, src.id] } %>
  <%= f.select :income_source_id, income_array %>
  <%= f.text_field :amount %>
  <%  curr_array = Currency.all.map { |cur| [cur.name, cur.id] } %>
  <%= f.select :currency_id, curr_array.sort %>
  <%= f.text_field :comments %>
  <%= f.submit "Create" %>
<% end %>

app/views/incomes/show.html.erb
<h1>Income#show</h1>
<p>Find me in app/views/income/show.html.erb</p>