config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :old_expenses
  resources :expenses
  resources :incomes
  resources :mobile

  resources :dashboard

  resources :work_expenses_in
  resources :work_expenses_out
  resources :old_incomes

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  before_filter :sanitize_expense_params
  before_action :set_expenses, on: :index

  def index
    @expenses.sort_by(&:created_at).reverse if @expenses.present?
  end

  def create    
    if params[:repeat_times].present? && params[:repeat_times].to_i > 1
      times = params[:repeat_times].to_i
      i = 0
      while i < times do
        month = (expense_params[:month].to_i + i) % 12
        year_add = (expense_params[:month].to_i + i) / 12
        Expense.create(expense_params.merge({month: month, year: year_add+expense_params[:year].to_i}))
        i += 1
      end
    else
      @expense = Expense.create(expense_params)
    end
    redirect_to action: "new"
  end

  def new
    @expense = Expense.new
  end

  def show
    @expense = Expense.find(params[:id])
  end

  def destroy
    @expense = Expense.find(params[:id])

    @expense.destroy!
    redirect_to action: "index"
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])

    if @expense.update(expense_params)
      redirect_to @expense
    else
      render 'edit'
    end
  end

  def expense_params
    params.require(:expense).permit(:category_id, :amount, :comments, 
                                    :year, :month, :currency_id, 
                                    :expense_type, :user_id)
  end

  def sanitize_expense_params
    params[:income_source_id] = params[:income_source_id].to_i
    params[:amount] = params[:amount].to_i
    params[:year] = params[:year].to_i
    params[:month] = params[:month].to_i
    params[:currency_id] = params[:currency_id].to_i
    params[:category_id] = params[:category_id].to_i
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_expenses
    if params[:filter].present?
      @expenses = Expense.where(year: params[:filter][:year]) if params[:filter][:year].present?
      @expenses = @expenses.where(month: params[:filter][:month]) if params[:filter][:month].present?
      @expenses = @expenses.joins(:category).where(categories: { hebrew_name: params[:filter][:category] }) if params[:filter][:category].present?
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/delete.html.erb
<h1>Expenses#delete</h1>
<p>Find me in app/views/expenses/delete.html.erb</p>

app/views/expenses/edit.html.erb
<h1>Expenses#update</h1>
<p>Find me in app/views/expenses/update.html.erb</p>

<h1>Edit expense</h1>

<%= form_for(@expense) do |f| %>

  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@expense.errors.count, "error") %> prohibited
        this expense from being saved:
      </h2>
      <ul>
        <% @expense.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :year %>
  <%= f.text_field :year, value: DateTime.now.year %>

  <%= f.label :month %>
  <%= f.text_field :month, value: DateTime.now.month %>
  <br>
  <%= f.label :category_id %>
  <%  expense_array = Category.active.map { |src| [src.hebrew_name, src.id] } %>
  <%= f.select :category_id, expense_array %>
  <br>
  <%= f.label :user_id %>
  <%  users_array = User.all.map { |src| [src.first_name, src.id] } %>
  <%= f.select :user_id, users_array %>
  <br>
  <%= f.label :expense_type %>
  <%= f.select :expense_type, Expense::expense_types %>
  <br>
  <%= f.label :currency_id %>
  <%  curr_array = Currency.all.map { |cur| [cur.name, cur.id] } %>
  <%= f.select :currency_id, curr_array.sort %>
  <br>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <br>
  <%= f.label :comments %>
  <%= f.text_field :comments %>
  <br>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<div class='container'>
<% if @expenses.present?%>
  <h1> By Month(<%= @expenses.last.month %>/<%= @expenses.last.year %>) </h1>
<%end%>

  <h2>Filter</h2>
  <% hash = {:CAD => 'C$', :ILS => '₪', :USD => '$'} %>
  <% unit = hash[params[:filter][:currency].to_sym] if params[:filter].present? %>
  <div class="filter_options_container">
    <form class="filter_form">
      <%= select("filter", "year", (2013..2020).to_a.unshift(""), selected: params[:filter].present? ? params[:filter][:year] : DateTime.now.year) %>
      <%= select("filter", "month", (1..12).to_a.unshift(""), selected: params[:filter].present? ? params[:filter][:month] : DateTime.now.month) %>
      <%= select("filter", "currency", ['CAD', 'ILS', 'USD'], selected: params[:filter].present? ? params[:filter][:currency] : 'CAD') %>
      <%= select("filter", "category", Category.active.pluck(:hebrew_name).unshift(""), selected: params[:filter].present? ? params[:filter][:category] : "") %>
      <input type="submit" value="Filter" />
    </form>
  </div>

  <% if params[:filter].present? %>
  <h2>Summary(<%= params[:filter][:currency] %>)</h2>
    <table class="table">
      <% total_expenses = @expenses.map{|item| item.currency.convert_to(params[:filter][:currency], item.amount) }.sum.to_i%>
      <tr><h3>Total Expenses: <%= number_to_currency(total_expenses, unit: unit, precision: 0) %></tr>
      <% total_income = Income.where(year: params[:filter][:year], month: params[:filter][:month]).map{|item| item.currency.convert_to(params[:filter][:currency], item.amount) }.sum.to_i %>
      <tr><h3>Total Income: <%= number_to_currency(total_income, unit: unit, precision: 0) %></tr>
      <tr><h3 style='color:green';>Total Saved: <%= number_to_currency(total_income - total_expenses, unit: unit, precision: 0) %></tr>
    </table>
  <% end %>

 
  <div class="row">
    <div class="col-sm-4">

  <% if params[:filter].present? && @expenses.present?  %>
    <% category_groups = @expenses.group_by{|e| [e.category.hebrew_name, e.currency.name]}.map{|k, v| { category: k[0], currency: k[1], amount: v.map(&:amount).sum } }.sort_by{|item| -item[:amount]} %>
    <h2>Grouped</h2>
    <table class="table table-hover">
      <tr>
        <th> Category </th>
        <th> Amount </th>
        <th> Currency </th>
      </tr>
      <% category_groups.each do |item| %>
        <tr>
          <td><%= item[:category] %></td>
          <td><%= item[:amount] %></td>
          <td><%= item[:currency] %></td>
        </tr>
      <% end %>
    </table>
    </div>

  <div class="col-sm-8">
  <h2>Expenses</h2>
  <table class="table table-hover">
    <tr>
      <th>year</th>
      <th>month</th>
      <th>category</th>
      <th>person</th>
      <th>amount</th>
      <th>comments</th>
    </tr>

    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.year %></td>
        <td><%= expense.month %></td>
        <td><%= expense.category.hebrew_name %></td>
        <td><%= expense.user.first_name %></td>
        <td><%= number_to_currency(expense.amount, precision: 0, unit: hash[expense.currency.name.to_sym]) %></td>
        <td><%= expense.comments %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Delete', expense_path(expense),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% end %>
</div>
</div>

app/views/expenses/new.html.erb
<h1>New Expense</h1>
<%= bootstrap_form_for @expense, url: {action: "create"} do |f| %>
  <%= f.text_field :year, value: DateTime.now.year %>
  <%= f.text_field :month, value: DateTime.now.month %>
  <%  expense_array = Category.active.map { |src| [src.hebrew_name, src.id] } %>
  <%= f.select :category_id, expense_array %>
  <%  users_array = User.all.map { |src| [src.first_name, src.id] } %>
  <%= f.select :user_id, users_array %>
  <%= f.select :expense_type, Expense::expense_types %>
  <%  curr_array = Currency.all.map { |cur| [cur.name, cur.id] } %>
  <%= f.select :currency_id, curr_array.sort %>
  <%= f.text_field :amount, prepend: "$" %>
  <%= f.text_field :comments %>
  <b>Repeat Times</b><input type="text" name="repeat_times" value="1" size= "2">
  <%= f.submit "Create" %>
<% end %>

app/views/expenses/quick.html.erb
<h1>New Expense</h1>
<%= bootstrap_form_for @expense, url: {action: "create"} do |f| %>
  <%= f.hidden_field :year, value: DateTime.now.year %>
  <%= f.text_field :month, value: DateTime.now.month %>
  <%  expense_array = Category.active.map { |src| [src.hebrew_name, src.id] } %>
  <%= f.select :category_id, expense_array %>
  <%  users_array = User.all.map { |src| [src.first_name, src.id] } %>
  <%= f.select :user_id, users_array %>
  <%= f.select :expense_type, Expense::expense_types %>
  <%  curr_array = Currency.all.map { |cur| [cur.name, cur.id] } %>
  <%= f.select :currency_id, curr_array.sort %>
  <%= f.text_field :amount, prepend: "$" %>
  <%= f.text_field :comments %>
  <b>Repeat Times</b><input type="text" name="repeat_times" value="1" size= "2">
  <%= f.submit "Create" %>
<% end %>

app/views/expenses/show.html.erb
<h1>Expenses#show</h1>
<p>Find me in app/views/expenses/show.html.erb</p>

<%= link_to 'Back', expenses_path %>
<p>
  <strong>Year:</strong>
  <%= @expense.year %>
</p>
<p>
  <strong>Month:</strong>
  <%= @expense.month %>
</p>
<p>
  <strong>Category:</strong>
  <%= @expense.category.hebrew_name %>
</p>
<p>
  <strong>Person:</strong>
  <%= @expense.user.first_name %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>
<p>
  <strong>Currency:</strong>
  <%= @expense.currency.name %>
</p>
<p>
  <strong>Comments:</strong>
  <%= @expense.comments %>
</p>